apiVersion: apps/v1
kind: Deployment
metadata:
  name: web2-all-deployment
spec:
  selector:
    matchLabels:
      app: web2-test
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: web2-test
    spec:
      containers:
      - name: web2-apache
        image: daviddtaylor/web2:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web2-all-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web2-test
